package com.carewash.entity;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    PROVIDER_ASSIGNED,
    PROVIDER_ON_THE_WAY,
    SERVICE_STARTED,
    SERVICE_COMPLETED,
    BOOKING_CANCELLED,
    SUBSCRIPTION_ACTIVATED,
    WASHES_LOW,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_RESUMED
}
