package com.carewash.entity;

public enum WhatsAppConversationState {
    NEW,
    MAIN_MENU,
    SELECTING_SERVICE,
    SELECTING_VEHICLE,
    SELECTING_ADDRESS,
    SELECTING_DATE,
    SELECTING_TIME,
    CONFIRMING_BOOKING,
    VIEWING_SERVICES,
    VIEWING_BOOKINGS,
    VIEWING_BOOKING_STATUS,
    SELECTING_BOOKING,
    SUPPORT,
    VIEWING_SUBSCRIPTION,
    VIEWING_SUBSCRIPTION_PLANS,
    COMPLETED
}




