export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
  SERVICE_PROVIDER: 'SERVICE_PROVIDER',
  SUPPORT_AGENT: 'SUPPORT_AGENT',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  CUSTOMER: 'CUSTOMER'
};

export const PERMISSIONS = {
  // User permissions
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_MANAGE_ROLES: 'USER_MANAGE_ROLES',

  // Service permissions
  SERVICE_VIEW: 'SERVICE_VIEW',
  SERVICE_CREATE: 'SERVICE_CREATE',
  SERVICE_UPDATE: 'SERVICE_UPDATE',
  SERVICE_DELETE: 'SERVICE_DELETE',

  // Pricing permissions
  PRICING_VIEW: 'PRICING_VIEW',
  PRICING_MANAGE: 'PRICING_MANAGE',

  // Booking permissions
  BOOKING_VIEW: 'BOOKING_VIEW',
  BOOKING_CREATE: 'BOOKING_CREATE',
  BOOKING_UPDATE: 'BOOKING_UPDATE',
  BOOKING_CANCEL: 'BOOKING_CANCEL',
  BOOKING_ASSIGN: 'BOOKING_ASSIGN',
  BOOKING_STATUS_UPDATE: 'BOOKING_STATUS_UPDATE',

  // Provider permissions
  PROVIDER_VIEW: 'PROVIDER_VIEW',
  PROVIDER_CREATE: 'PROVIDER_CREATE',
  PROVIDER_UPDATE: 'PROVIDER_UPDATE',
  PROVIDER_ASSIGN: 'PROVIDER_ASSIGN',

  // Customer specific (Own resources)
  OWN_BOOKING_VIEW: 'OWN_BOOKING_VIEW',
  OWN_BOOKING_CREATE: 'OWN_BOOKING_CREATE',
  OWN_BOOKING_CANCEL: 'OWN_BOOKING_CANCEL',
  OWN_VEHICLE_MANAGE: 'OWN_VEHICLE_MANAGE',
  OWN_ADDRESS_MANAGE: 'OWN_ADDRESS_MANAGE',

  // Service Job (Provider specific)
  SERVICE_JOB_VIEW: 'SERVICE_JOB_VIEW',
  SERVICE_JOB_ACCEPT: 'SERVICE_JOB_ACCEPT',
  SERVICE_JOB_STATUS_UPDATE: 'SERVICE_JOB_STATUS_UPDATE',
  SERVICE_JOB_COMPLETE: 'SERVICE_JOB_COMPLETE',

  // Additional modules
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_MANAGE: 'PAYMENT_MANAGE',
  REFUND_MANAGE: 'REFUND_MANAGE',

  COUPON_VIEW: 'COUPON_VIEW',
  COUPON_MANAGE: 'COUPON_MANAGE',

  SUPPORT_VIEW: 'SUPPORT_VIEW',
  SUPPORT_MANAGE: 'SUPPORT_MANAGE',

  REPORT_VIEW: 'REPORT_VIEW',
  
  NOTIFICATION_VIEW: 'NOTIFICATION_VIEW',
  NOTIFICATION_MANAGE: 'NOTIFICATION_MANAGE',

  SYSTEM_SETTINGS_VIEW: 'SYSTEM_SETTINGS_VIEW',
  SYSTEM_SETTINGS_MANAGE: 'SYSTEM_SETTINGS_MANAGE',
  
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_MANAGE: 'PROFILE_MANAGE'
};
